### ISSUE TITLE
Improve readability of settings

### ISSUE THREAD

**Issue by f-bader** [merill/idPowerToys#1]
The settings are a touch to dark. Would be great if you could use a lighter color for better readability 

![image](https://user-images.githubusercontent.com/3834359/224926088-e3fb64b6-1a7b-4212-8223-bd60e4649ce6.png)

**Comment by merill** [comment]
Tx Fabian, for some reason this is only happening in Windows.
![CleanShot 2023-03-14 at 23 30 49@2x](https://user-images.githubusercontent.com/1288081/225001646-2ac290b7-4aae-4cda-90c1-a7627bce6cf9.png)

For now I'll disable the dark theme support and add it back once tested on all platforms
