### ISSUE TITLE
Question: idpowertoys.com data usage/protection 

### ISSUE THREAD

**Issue by Nick-JXN** [merill/idPowerToys#12]
Question: 

If we use idPoweToys through the web (idpowertoys.com) how is the data is being used? Also, what security standards are in place to protect the data that goes through the site?

**Comment by OlivierLumeau** [comment]
I have the same question: 
How can be be sure that the security relative Data (about Conditional Access) stays private. 
Does idPowerToys CA report respect the GPRD convention?

**Comment by merill** [comment]
Hey folks, the source code of idPowerToys is published in this repo. The application does not log, store or cache any information outside of the method names and exception errors with stack trace. I plan to log the tenantId in an upcoming release to track usage metrics.

There is a beta desktop version available that you can download and run (plus use your own single tenant application). In the desktop version all of the tokens, graph api calls and generated presentation run locally on your desktop.

See https://github.com/merill/idPowerToys/releases/tag/v0.1.0-alpha

I am planning to make a PowerShell version which will work in a similar manner to the desktop version and run locally on your desktop.

**Comment by merill** [comment]
Hey folks, the source code of idPowerToys is published in this repo. The application does not log, store or cache any information outside of the method names and exception errors with stack trace. I plan to log the tenantId in an upcoming release to track usage metrics.

There is a beta desktop version available that you can download and run (plus use your own single tenant application). In the desktop version all of the tokens, graph api calls and generated presentation run locally on your desktop.

See https://github.com/merill/idPowerToys/releases/tag/v0.1.0-alpha

I am planning on making a PowerShell version which will work in a similar manner to the desktop version.

**Comment by merill** [comment]
Hi Olivier,

No data is saved on the server.

When you click Generate the Web server queries Graph API to retrieve your tenants CA policies,  creates the PowerPoint deck in memory and streams it down to your browser. 

None of your CA policies, tokens and not even your username is stored the server. 

Hope that helps.
