### ISSUE TITLE
Blank presentation

### ISSUE THREAD

**Issue by planet4** [merill/idPowerToys#5]
Thanks for sharing this. I only get the first page in the powerpoint. I use the automatic generation and my admin account. What could be wrong?

**Comment by merill** [comment]
Can you try refreshing the page to make sure you have the latest version loaded?

**Comment by planet4** [comment]
I just tried Edge in a privite window. Never use edge normally but same problem.

**Comment by RobTrehy** [comment]
I can confirm I am also experiencing the save behaviour with both Edge and Chrome.

**Comment by merill** [comment]
I'm not able to replicate on my tenants. Is there a demo tenant where you can repro the issue?

**Comment by The-Kurd** [comment]
Thanks for this great tool. I can confirm same problem with a demo tenant i have. Manual report works.

**Comment by merill** [comment]
Awesome. Would you be able to create an account for me in your demo tenant with global reader access?

Please send the login details to merill@merill.net. 

Alternatively you can message me directly on Discord at https://discord.gg/HaTwKYvX

**Comment by The-Kurd** [comment]
Credential sent to you :)

**Comment by merill** [comment]
Got it. Testing now.

**Comment by merill** [comment]
It's a very odd issue. Works fine when I run the generation locally but the Graph API call fails when running in Azure just for this tenant. 

In the interim, can you please try the new desktop version and let me know if you are running into the same issue or not?

You can get the desktop version at https://github.com/merill/idPowerToys/releases/tag/v0.1.0-alpha

**Comment by The-Kurd** [comment]
**Web version:** Still problem. Re registered Enterprise Application--> Gives error "Something went wrong, please try again". First time i did also see this error message, but did work after some time(1+ hour).

Dektop app: Works as intended reporting info page with each CA policy.

Will test more.

**Comment by The-Kurd** [comment]
@merill Tried again today without doing any changes on web version: No error message and ppt generated with all CA.

So re-registering the application seems to have solved the problem, but for some reason it gives the error messages several hours after registering. Might also just be demo tenants...

All good for now

**Comment by RobTrehy** [comment]
The web version just worked for me again now - I did not re-register the application, no changes were made between now and when I did have the issue.

**Comment by planet4** [comment]
Same for me. It just works now
